-- MySQL Script generated by MySQL Workbench
-- mié 24 feb 2021 20:02:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema soccerSmash
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soccerSmash
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soccerSmash` ;
USE `soccerSmash` ;

-- -----------------------------------------------------
-- Table `soccerSmash`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccerSmash`.`Player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccerSmash`.`Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccerSmash`.`Teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccerSmash`.`League`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccerSmash`.`League` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccerSmash`.`League_has_Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccerSmash`.`League_has_Teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `League_id` INT NOT NULL,
  `tem_id` INT NOT NULL,
  `isActive` TINYINT NULL,
  INDEX `fk_League_has_Teams_Teams1_idx` (`tem_id` ASC) VISIBLE,
  INDEX `fk_League_has_Teams_League_idx` (`League_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_League_has_Teams_League`
    FOREIGN KEY (`League_id`)
    REFERENCES `soccerSmash`.`League` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_League_has_Teams_Teams1`
    FOREIGN KEY (`tem_id`)
    REFERENCES `soccerSmash`.`Teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccerSmash`.`Season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccerSmash`.`Season` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isActive` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `n_tems` VARCHAR(45) NULL,
  `League_id` INT NOT NULL,
  `id_winner_team` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Season_League1_idx` (`League_id` ASC) VISIBLE,
  INDEX `fk_Season_League_has_Teams1_idx` (`id_winner_team` ASC) VISIBLE,
  CONSTRAINT `fk_Season_League1`
    FOREIGN KEY (`League_id`)
    REFERENCES `soccerSmash`.`League` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Season_League_has_Teams1`
    FOREIGN KEY (`id_winner_team`)
    REFERENCES `soccerSmash`.`League_has_Teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccerSmash`.`type_match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccerSmash`.`type_match` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL COMMENT 'reference: \n-Normal Match\n-Semifinal match\n-final Match',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccerSmash`.`Matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccerSmash`.`Matches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isFinished` VARCHAR(45) NULL,
  `Season_id` INT NOT NULL,
  `type_match_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Matches_Season1_idx` (`Season_id` ASC) VISIBLE,
  INDEX `fk_Matches_type_match1_idx` (`type_match_id` ASC) VISIBLE,
  CONSTRAINT `fk_Matches_Season1`
    FOREIGN KEY (`Season_id`)
    REFERENCES `soccerSmash`.`Season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matches_type_match1`
    FOREIGN KEY (`type_match_id`)
    REFERENCES `soccerSmash`.`type_match` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccerSmash`.`Teams_has_Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccerSmash`.`Teams_has_Player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_team` INT NOT NULL,
  `id_player` INT NOT NULL,
  `isActive` TINYINT NULL,
  INDEX `fk_Teams_has_Player_Player1_idx` (`id_player` ASC) VISIBLE,
  INDEX `fk_Teams_has_Player_Teams1_idx` (`id_team` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Teams_has_Player_Teams1`
    FOREIGN KEY (`id_team`)
    REFERENCES `soccerSmash`.`Teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teams_has_Player_Player1`
    FOREIGN KEY (`id_player`)
    REFERENCES `soccerSmash`.`Player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccerSmash`.`Action_in_match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccerSmash`.`Action_in_match` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccerSmash`.`matchlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccerSmash`.`matchlog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `Player_in_team` INT NOT NULL,
  `id_action` INT NOT NULL,
  `id_match` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_matchlog_Teams_has_Player1_idx` (`Player_in_team` ASC) VISIBLE,
  INDEX `fk_matchlog_Action_in_match1_idx` (`id_action` ASC) VISIBLE,
  INDEX `fk_matchlog_Matches1_idx` (`id_match` ASC) VISIBLE,
  CONSTRAINT `fk_matchlog_Teams_has_Player1`
    FOREIGN KEY (`Player_in_team`)
    REFERENCES `soccerSmash`.`Teams_has_Player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchlog_Action_in_match1`
    FOREIGN KEY (`id_action`)
    REFERENCES `soccerSmash`.`Action_in_match` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchlog_Matches1`
    FOREIGN KEY (`id_match`)
    REFERENCES `soccerSmash`.`Matches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soccerSmash`.`Teams_has_Matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soccerSmash`.`Teams_has_Matches` (
  `id_team_has_matches` INT NOT NULL AUTO_INCREMENT,
  `Matches_id` INT NOT NULL,
  `goals` VARCHAR(45) NULL,
  `Teams_id` INT NOT NULL,
  PRIMARY KEY (`id_team_has_matches`),
  INDEX `fk_Teams_has_Matches_Matches1_idx` (`Matches_id` ASC) VISIBLE,
  INDEX `fk_Teams_has_Matches_Teams1_idx` (`Teams_id` ASC) VISIBLE,
  CONSTRAINT `fk_Teams_has_Matches_Matches1`
    FOREIGN KEY (`Matches_id`)
    REFERENCES `soccerSmash`.`Matches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teams_has_Matches_Teams1`
    FOREIGN KEY (`Teams_id`)
    REFERENCES `soccerSmash`.`Teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `soccerSmash`.`Player`
-- -----------------------------------------------------
START TRANSACTION;
USE `soccerSmash`;
INSERT INTO `soccerSmash`.`Player` (`id`, `nombre`) VALUES (1, 'Messi');
INSERT INTO `soccerSmash`.`Player` (`id`, `nombre`) VALUES (2, 'Ronaldo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `soccerSmash`.`Teams`
-- -----------------------------------------------------
START TRANSACTION;
USE `soccerSmash`;
INSERT INTO `soccerSmash`.`Teams` (`id`, `team`) VALUES (1, 'Barcelona');
INSERT INTO `soccerSmash`.`Teams` (`id`, `team`) VALUES (2, 'Real Madrid');

COMMIT;


-- -----------------------------------------------------
-- Data for table `soccerSmash`.`League`
-- -----------------------------------------------------
START TRANSACTION;
USE `soccerSmash`;
INSERT INTO `soccerSmash`.`League` (`id`, `title`) VALUES (1, 'liga Santander');
INSERT INTO `soccerSmash`.`League` (`id`, `title`) VALUES (2, 'liga Rey');

COMMIT;


-- -----------------------------------------------------
-- Data for table `soccerSmash`.`League_has_Teams`
-- -----------------------------------------------------
START TRANSACTION;
USE `soccerSmash`;
INSERT INTO `soccerSmash`.`League_has_Teams` (`id`, `League_id`, `tem_id`, `isActive`) VALUES (1, 1, 1, 1);
INSERT INTO `soccerSmash`.`League_has_Teams` (`id`, `League_id`, `tem_id`, `isActive`) VALUES (2, 1, 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `soccerSmash`.`Season`
-- -----------------------------------------------------
START TRANSACTION;
USE `soccerSmash`;
INSERT INTO `soccerSmash`.`Season` (`id`, `isActive`, `created_at`, `n_tems`, `League_id`, `id_winner_team`) VALUES (1, '1', 'creada ahora', '2', 1, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `soccerSmash`.`type_match`
-- -----------------------------------------------------
START TRANSACTION;
USE `soccerSmash`;
INSERT INTO `soccerSmash`.`type_match` (`id`, `type`) VALUES (1, 'partido normal');

COMMIT;


-- -----------------------------------------------------
-- Data for table `soccerSmash`.`Matches`
-- -----------------------------------------------------
START TRANSACTION;
USE `soccerSmash`;
INSERT INTO `soccerSmash`.`Matches` (`id`, `isFinished`, `Season_id`, `type_match_id`) VALUES (1, '0', 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `soccerSmash`.`Teams_has_Player`
-- -----------------------------------------------------
START TRANSACTION;
USE `soccerSmash`;
INSERT INTO `soccerSmash`.`Teams_has_Player` (`id`, `id_team`, `id_player`, `isActive`) VALUES (1, 1, 1, 1);
INSERT INTO `soccerSmash`.`Teams_has_Player` (`id`, `id_team`, `id_player`, `isActive`) VALUES (2, 2, 2, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `soccerSmash`.`Action_in_match`
-- -----------------------------------------------------
START TRANSACTION;
USE `soccerSmash`;
INSERT INTO `soccerSmash`.`Action_in_match` (`id`, `action`) VALUES (1, 'Gol');
INSERT INTO `soccerSmash`.`Action_in_match` (`id`, `action`) VALUES (2, 'Tarjeta roja');
INSERT INTO `soccerSmash`.`Action_in_match` (`id`, `action`) VALUES (DEFAULT, 'Tarjeta Amarilla');

COMMIT;


-- -----------------------------------------------------
-- Data for table `soccerSmash`.`matchlog`
-- -----------------------------------------------------
START TRANSACTION;
USE `soccerSmash`;
INSERT INTO `soccerSmash`.`matchlog` (`id`, `description`, `Player_in_team`, `id_action`, `id_match`) VALUES (1, 'gol de cristiano ronaldo', 2, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `soccerSmash`.`Teams_has_Matches`
-- -----------------------------------------------------
START TRANSACTION;
USE `soccerSmash`;
INSERT INTO `soccerSmash`.`Teams_has_Matches` (`id_team_has_matches`, `Matches_id`, `goals`, `Teams_id`) VALUES (1, 1, '2', 1);
INSERT INTO `soccerSmash`.`Teams_has_Matches` (`id_team_has_matches`, `Matches_id`, `goals`, `Teams_id`) VALUES (2, 1, '5', 2);

COMMIT;

